/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 * Author:  Gilberto Manunta
 * Created: 9-mag-2017
 */
/* username: gilberto
 * password: ammdb
 */
CREATE TABLE postType (
    posttype_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(32)
);

CREATE TABLE utenti (
    user_id  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(256) UNIQUE,
    cognome VARCHAR(256),
    password VARCHAR(256) NOT NULL,
    urlFotoProfilo VARCHAR(256),
    fraseDiPresentazione VARCHAR(512),
    dataDiNascita DATE
);

CREATE TABLE posts (
    post_id  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content VARCHAR(1024),
    tipo INTEGER,
    FOREIGN KEY (tipo) REFERENCES postType(id),
    autore INTEGER,
    FOREIGN KEY (autore) REFERENCES utenti(id)
);

INSERT INTO utenti (id, nome, cognome, password, urlFotoProfilo, fraseDiPresentazione, dataDiNascita)
VALUES (default,
        'Gilberto',
        'Manunta',
        '123456789',
        'Immagini/profilo1.jpg',
		'Ciao a tutti',
        '1996-01-08');

INSERT INTO utenti (id, nome, cognome, password, urlFotoProfilo, fraseDiPresentazione, dataDiNascita)
VALUES (default,
        'Marco',
        'Iervolino',
        'cosavuoi1',
        'Immagini/profilo2.jpg',
		'Cosa vuoi?',
        '1996-06-06');
		
INSERT INTO utenti (id, nome, cognome, password, urlFotoProfilo, fraseDiPresentazione, dataDiNascita)
VALUES (default,
        'Mauro',
        'Marini',
        'busho97', 
		'Immagini/profilo3.png',
		'Bellaaaa',
        '1996-04-24');
		
INSERT INTO postType (id, nome)
VALUES (default,
		'TEXT');
		
INSERT INTO postType (id, nome)
VALUES (default,
		'IMAGE');

INSERT INTO postType (id, nome)
VALUES (default,
		'LINK');

--Popolamento tabella Post
INSERT INTO posts (id, content, type, author)
VALUES (default,
        'Lorem ipsum!',
        1,
        1);
		
INSERT INTO posts (id, content, type, author)
VALUES (default,
        'Immagini/incidente.jpg',
        2,
        2);
		
INSERT INTO posts (id, content, type, author)
VALUES (default,
        'Dolores de panza',
        1,
        3);
		
INSERT INTO posts (id, content, type, author)
VALUES (default,
        'https://www.youtube.com',
        3,
        1);